"""update chat_session table

Revision ID: 4ca16017adac
Revises: 67f801ec5c26
Create Date: 2026-07-19 17:51:04.463724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ca16017adac'
down_revision: Union[str, Sequence[str], None] = '67f801ec5c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('chat_session', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('chat_session', sa.Column('llm_call_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('chat_session', sa.Column('answer_accuracy', sa.Float(), nullable=True))
    op.add_column('chat_session', sa.Column('chat_created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('chat_session', sa.Column('chat_ended_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('chat_session', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('chat_session', 'chat_ended_at')
    op.drop_column('chat_session', 'chat_created_at')
    op.drop_column('chat_session', 'answer_accuracy')
    op.drop_column('chat_session', 'llm_call_count')
    op.drop_column('chat_session', 'summary')
    op.drop_column('chat_session', 'topic')
    # ### end Alembic commands ###
