"""drop user_id fk, add username to agent_log

Revision ID: 7ca302cc4a14
Revises: e9d65762f908
Create Date: 2026-08-06 21:42:41.873636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca302cc4a14'
down_revision: Union[str, Sequence[str], None] = 'e9d65762f908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_log', sa.Column('username', sa.String(), nullable=False, server_default='unknown'))
    op.drop_constraint(op.f('agent_log_user_id_fkey'), 'agent_log', type_='foreignkey')
    op.drop_constraint(op.f('query_events_user_id_fkey'), 'query_events', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('query_events_user_id_fkey'), 'query_events', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('agent_log_user_id_fkey'), 'agent_log', 'users', ['user_id'], ['id'])
    op.drop_column('agent_log', 'username')
    # ### end Alembic commands ###
