"""drop user_id fk from chat_session

Revision ID: 922d507906d7
Revises: 7ca302cc4a14
Create Date: 2026-08-06 22:03:43.763218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922d507906d7'
down_revision: Union[str, Sequence[str], None] = '7ca302cc4a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_session_user_id_fkey'), 'chat_session', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('chat_session_user_id_fkey'), 'chat_session', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
