"""add agent_logs table

Revision ID: e9d65762f908
Revises: 3a39eef2e4a8
Create Date: 2026-07-31 16:34:50.953795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d65762f908'
down_revision: Union[str, Sequence[str], None] = '3a39eef2e4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('router_decision', sa.JSON(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('tool_params', sa.JSON(), nullable=True),
    sa.Column('tool_response', sa.JSON(), nullable=True),
    sa.Column('maker_checker_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_log')
    # ### end Alembic commands ###
